### ISSUE TITLE
Loss and Dice during model training

### ISSUE THREAD

**Issue by hangingter** [jianpengz/ConResNet#1]
During my training in another task, I found that the Dice improved slowly.
May I ask about the change of **loss** and verification set **dice** during the model training both in BraTS and Pancreas-CT?
Thank you!

**Comment by jianpengz** [comment]
Convergence in our experiments was normal (see the training loss and validation dice of brain whole tumor in the following). 

![image](https://user-images.githubusercontent.com/21073209/101486909-4aae6280-39ad-11eb-8ada-c3817c64da9d.png)
