### ISSUE TITLE
the effect of weight standardization algorithm

### ISSUE THREAD

**Issue by xwjBupt** [jianpengz/ConResNet#2]
Hi! 

thanks for sharing the code! it is a wonderful work! But i am wondering have you guys tested the effect of WS? what is you baseline results without WS?

Thank you!

**Comment by jianpengz** [comment]
All of my experiments, including baseline, were equipped with WS. I didn't test the baseline w/o WS in this work. But I observed slightly better performance in my previous practice.

**Comment by xwjBupt** [comment]
ok,i understand thanks !!
