### ISSUE TITLE
The preprocess of pancreas dataset

### ISSUE THREAD

**Issue by hxshust** [jianpengz/ConResNet#3]
Hi,thanks for your sharing code.It is a  very impressive  work!

Can you please add the preprocessing file of the pancreas dataset?
 I tried to modify the preprocessing file of the Brats dataset, but I encountered some problems.

Thank you !

**Comment by jianpengz** [comment]
Please refer to the dataloader for the pancreas dataset in dataset/PancreasDataSet.py

**Comment by Fazzy101** [comment]
Hi, Impressive job!

Please Can you include link to the data and image_id_list for training purposes. Thanks!
