### ISSUE TITLE
Link to data and  image_id_list

### ISSUE THREAD

**Issue by Fazzy101** [jianpengz/ConResNet#4]
Hi, Impressive job!

Please Can you include link to the data and image_id_list for training purposes. Thanks!

**Comment by jianpengz** [comment]
The test-id of four folds are:
"fold1": [10, 68, 44, 7, 70, 43, 80, 19, 3, 57, 74, 20, 50, 46, 9, 25, 6, 71, 72, 29],
"fold2": [60, 30, 37, 81, 64, 56, 79, 48, 76, 31, 27, 23, 16, 42, 63, 34, 65, 32, 24, 82],
"fold3": [11, 17, 15, 40, 18, 53, 35, 51, 26, 36, 8, 13, 67, 22, 12, 52, 59, 54, 66, 33, 73],
"fold4": [14, 77, 45, 58, 2, 78, 28, 21, 41, 1, 55, 61, 39, 38, 75, 4, 5, 47, 49, 62, 69]

The remaining cases are used for training in each fold.
